export const comics = [
    {
        "id":"100001",
        "titulo": "Superman",
        "vol": "1",
        "desc":"La historia sigue a Clark Kent, un periodista en el Daily Planet de Metrópolis, que lleva una doble vida como el superhéroe",
        "image":"/asset/img/Superman-Tomo1.jpg",
        "price":"15000",
        "stock":"10",
        "editorial":"Polis Metro",
    },
    {
        "id":"100002",
        "titulo": "Batman",
        "vol": "1",
        "desc":"La historia sigue a Bruce Wayne, un multimillonario que lucha contra el crimen en Gotham City como el justiciero enmascarado",
        "image":"/asset/img/Batman-Tomo1.jpg",
        "price":"16990",
        "stock":"5",
        "editorial":"Tic Go",
    },
    {
        "id":"100003",
        "titulo": "Flash",
        "vol": "1",
        "desc":"La historia trata de Barry Allen, un científico forense que adquiere la capacidad de moverse a velocidades extremas",
        "image":"/asset/img/Flash-Tomo1.jpg",
        "price":"15990",
        "stock":"14",
        "editorial":"Tralcen",
    },
    {
        "id":"100004",
        "titulo": "Wonder Woman",
        "vol": "1",
        "desc":"La historia sigue a Diana, una guerrera amazona de Themyscira, que decide intervenir en los asuntos de la humanidad",
        "image":"/asset/img/MujerMaravilla-Tomo1.jpg",
        "price":"17990",
        "stock":"8",
        "editorial":"Cira Mysthe",
    },
    {
        "id":"100005",
        "titulo": "Shazam",
        "vol": "1",
        "desc":"La historia trata de Billy Batson, un adolescente que recibe poderes mágicos de un antiguo mago, lo que le permite transformarse en un antiguo guerrero",
        "image":"/asset/img/Shazam-Portada1.jpg",
        "price":"18990",
        "stock":"20",
        "editorial":"Sonllybi",
    },
    {
        "id":"100006",
        "titulo": "Black Adam",
        "vol": "1",
        "desc":"La historia sigue a Teth-Adam, un antiguo guerrero egipcio que recibe poderes sobrenaturales de los dioses y se convierte en un poderoso enemigo",
        "image":"/asset/img/Black-Adam-Portada.jpg",
        "price":"16990",
        "stock":"20",
        "editorial":"Sonllybi",
    },
    {
        "id":"100007",
        "titulo": "Linterna Verde",
        "vol": "1",
        "desc":"La historia sigue a Hal Jordan, un piloto de pruebas que se une a los Linterna Verde, un cuerpo intergaláctico",
        "image":"/asset/img/Literna-Verde-Portada.jpg",
        "price":"15990",
        "stock":"13",
        "editorial":"Danjor",
    },
    {
        "id":"100008",
        "titulo": "Spiderman",
        "vol": "1",
        "desc":"La historia sigue a Peter Parker, un estudiante de secundaria que adquiere habilidades arácnidas extraordinarias",
        "image":"/asset/img/Spider-Man-Portada.jpg",
        "price":"19990",
        "stock":"9",
        "editorial":"Klynbroo",
    },
    {
        "id":"100009",
        "titulo": "Ironman",
        "vol": "1",
        "desc":"La historia sigue a Tony Stark, un multimillonario empresario e inventor que, tras ser secuestrado y casi morir",
        "image":"/asset/img/Iron-Man-Portada.jpg",
        "price":"14990",
        "stock":"5",
        "editorial":"Yorknew",
    },
    {
        "id":"100010",
        "titulo": "Thor",
        "vol": "1",
        "desc":"La historia sigue a Thor, el dios nórdico del trueno, que es desterrado a la Tierra por su arrogancia y comportamiento impulsivo",
        "image":"/asset/img/Thor-Portada.jpg",
        "price":"17990",
        "stock":"10",
        "editorial":"Gardas",
    },
    {
        "id":"100011",
        "titulo": "Deadpool",
        "vol": "1",
        "desc":"La historia sigue a Wade Wilson, un exsoldado de élite convertido en mercenario que se somete a un experimento fallido",
        "image":"/asset/img/Dead-pool.jpg",
        "price":"16990",
        "stock":"1",
        "editorial":"Forcex",
    },
    {
        "id":"100012",
        "titulo": "Hulk",
        "vol": "1",
        "desc":"La historia sigue a Bruce Banner, un científico que se transforma en la criatura verde Hulk tras un accidente con radiación",
        "image":"/asset/img/Hulk-portada.jpg",
        "price":"11990",
        "stock":"12",
        "editorial":"Maga",
    },
];



export const mangas = [
    {
        "id":"200001",
        "titulo": "Oshi no ko - new idol",
        "vol": "1",
        "desc":"Es un manga que narra la historia de Gorou, un médico que reencarna como el hijo de su ídolo, la estrella del pop Ai Hoshino. Renacido",
        "image":"/asset/img/Oshi-no-ko.jpg",
        "price":"15000",
        "stock":"10",
        "editorial":"Polis Metro",
    },
    {
        "id":"200002",
        "titulo": "shuumatsu no valkyrie",
        "vol": "1",
        "desc":"Es un manga sobre un torneo épico donde 13 dioses se enfrentan a 13 héroes humanos para decidir el destino de la humanidad...",
        "image":"/asset/img/Shu.jpg",
        "price":"30000",
        "stock":"15",
        "editorial":"Shueisha ",
    },
    {
        "id":"200003",
        "titulo": "Boku no Kokoro no Yabai Yatsu",
        "vol": "1",
        "desc":"Es un manga que sigue a Ichikawa Kyotaro, un estudiante de secundaria introvertido con pensamientos oscuros y...",
        "image":"/asset/img/Boku.jpg",
        "price":"25000",
        "stock":"8",
        "editorial":"Akita Shoten",
    },
    {
        "id":"200004",
        "titulo": "Digimon adventure ZT",
        "vol": "1",
        "desc":"Es una secuela de la serie original Digimon Adventure que sigue a un nuevo grupo de niños elegidos, incluidos Daisuke, Hikari y Takeru...",
        "image":"/asset/img/Digi.jpg",
        "price":"12000",
        "stock":"14",
        "editorial":"Toei Animation",
    },
    {
        "id":"200005",
        "titulo": "Nanatsu No Taizai",
        "vol": "1",
        "desc":"Es un manga y anime sobre un grupo de caballeros deshonrados llamados Los Siete Pecados Capitales, liderados por Meliodas. Conocidos...",
        "image":"/asset/img/Nanat.jpg",
        "price":"20000",
        "stock":"7",
        "editorial":"Kōdansha",
    },
    {
        "id":"200006",
        "titulo": "Four knight of the Apocalypse",
        "vol": "1",
        "desc":"Es una secuela de Nanatsu no Taizai que sigue a Tristan Liones, el hijo de Meliodas y Elizabeth, quien hereda los poderes de sus padres...",
        "image":"/asset/img/Cab.jpg",
        "price":"25000",
        "stock":"14",
        "editorial":"Norma Editorial",
    },
    {
        "id":"200007",
        "titulo": "Mobile Suit Gundam 00",
        "vol": "1",
        "desc":"Es una serie ambientada en un futuro donde la humanidad depende de ascensores espaciales para obtener energía solar. Un...",
        "image":"/asset/img/Gun.jpg",
        "price":"10000",
        "stock":"6",
        "editorial":"BEC",
    },
    {
        "id":"200008",
        "titulo": "One Punch Man - Saitama",
        "vol": "1",
        "desc":"Es una serie sobre Saitama, un hombre aparentemente común que se convierte en superhéroe después de entrenar intensamente...",
        "image":"/asset/img/Punch.jpg",
        "price":"25000",
        "stock":"5",
        "editorial":"Shūeisha",
    },
    {
        "id":"200009",
        "titulo": "The Jack the Ripper Case Files",
        "vol": "1",
        "desc":"Es un manga que narra la historia de Gorou, un médico que reencarna como el hijo de su ídolo, la estrella del pop Ai Hoshino. Renacido",
        "image":"/asset/img/Jack.jpg",
        "price":"15990",
        "stock":"21",
        "editorial":"George G. Harrap & Co Ltd,",
    },
    {
        "id":"200010",
        "titulo": "Fate: Grand Order",
        "vol": "1",
        "desc":"Es un manga y serie de la franquicia Fate donde los jugadores son Maestros que viajan a través del tiempo para corregir anomalías históricas...",
        "image":"/asset/img/Fate.jpg",
        "price":"10000",
        "stock":"5",
        "editorial":"Lerche",
    },
    {
        "id":"200011",
        "titulo": "High school DXD - Hero",
        "vol": "1",
        "desc":"Sigue a Issei Hyoudou, un estudiante de secundaria pervertido que es asesinado en su primera cita y resucitado como demonio por Rias Gremory, una...",
        "image":"/asset/img/Dxd.jpg",
        "price":"30000",
        "stock":"3",
        "editorial":"Fujimi Shobo",
    },
    {
        "id":"200012",
        "titulo": "High School Of The Dead",
        "vol": "1",
        "desc":"sigue a un grupo de estudiantes de secundaria que luchan por sobrevivir tras un apocalipsis zombi. Liderados por Takashi Komuro, el grupo, junto...",
        "image":"/asset/img/Dead.jpg",
        "price":"17000",
        "stock":"9",
        "editorial":"Fujimi Shobo",
    },
];