export const productos = [
    {
        "id":"000001",
        "titulo": "Superman",
        "vol": "1",
        "desc":"La historia sigue a Clark Kent, un periodista en el Daily Planet de Metrópolis, que lleva una doble vida como el superhéroe",
        "img":"../Assets/img/productos/superman",
        "price":"15000",
        "stock":"10",
        "editorial":"Polis Metro",
    },
    {
        "id":"000002",
        "titulo": "Batman",
        "vol": "1",
        "desc":"La historia sigue a Bruce Wayne, un multimillonario que lucha contra el crimen en Gotham City como el justiciero enmascarado",
        "price":"16990",
        "stock":"5",
        "editorial":"Tic Go",
    },
    {
        "id":"000003",
        "titulo": "Flash",
        "vol": "1",
        "desc":"La historia trata de Barry Allen, un científico forense que adquiere la capacidad de moverse a velocidades extremas",
        "price":"15990",
        "stock":"14",
        "editorial":"Tralcen",
    },
    {
        "id":"000004",
        "titulo": "Wonder Woman",
        "vol": "1",
        "desc":"La historia sigue a Diana, una guerrera amazona de Themyscira, que decide intervenir en los asuntos de la humanidad",
        "price":"17990",
        "stock":"8",
        "editorial":"Cira Mysthe",
    },
    {
        "id":"000005",
        "titulo": "Shazam",
        "vol": "1",
        "desc":"La historia trata de Billy Batson, un adolescente que recibe poderes mágicos de un antiguo mago, lo que le permite transformarse en un antiguo guerrero",
        "price":"18990",
        "stock":"20",
        "editorial":"Sonllybi",
    },
    {
        "id":"000005",
        "titulo": "Black Adam",
        "vol": "1",
        "desc":"La historia sigue a Teth-Adam, un antiguo guerrero egipcio que recibe poderes sobrenaturales de los dioses y se convierte en un poderoso enemigo",
        "price":"18990",
        "stock":"20",
        "editorial":"Sonllybi",
    },
];